name: Cyberacademy CI/CD on master

on:  
  push:
    branches:
      - master

jobs:  
  deploy:
    name: CyberAcademy Deploy from master
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Perintah Linux
        run: |
          git status
          ls -lah
          id
          echo "Alkhairunas Riyuska is deploying to prod"